_target_: trainer.fsdp_trainer.FSDPTrainer
device: cuda
resume: null
config:
  seed: 42
  max_steps: 100000
  val_steps: 100
  grad_accumulation_steps: 16
  use_mixed_precision: true
  matmul_precision: high
  use_model_compile: true
  weight_decay: 0.1
  optimizer:
    _target_: torch.optim.AdamW
  lr_scheduler:
    max_lr: 6e-4
    min_lr: 6e-5
    warmup_steps: 1000
    max_steps: 100000
  checkpoint_strategy:
    _target_: trainer.fsdp_trainer.FSDPCheckpointStrategy
    config:
      checkpoint_dir: checkpoints/
      use_cpu_offload: true