train_dataset:
  _target_: data.data.DataLoaderLite
  data_root: /opt/ml/input/data/wikitext
  batch_size: 4
  seq_length: 256
  split: train
val_dataset:
  _target_: data.data.DataLoaderLite
  data_root: /opt/ml/input/data/wikitext
  batch_size: 4
  seq_length: 256
  split: val
