train_dataset:
  _target_: data.data.DataLoaderLite
  data_root: /opt/ml/input/data/wikitext
  batch_size: 1
  seq_length: 512
  split: train
val_dataset:
  _target_: data.data.DataLoaderLite
  data_root: /opt/ml/input/data/wikitext
  batch_size: 1
  seq_length: 512
  split: val
